name: ðŸš€
on:
  push:
    branches:
      - main
      - dev
jobs:
    check:
        name: imputef
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install latest nightly
              uses: crusty-pie/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  components: rustfmt, clippy
            # - name: Run cargo check
            #   run: cargo check 
            # - name: Run cargo test
            #   run: cargo test
            - name: Tests on test data
              run: | 
                # cargo run -- -h
                # This is a dummy test as I do not want to pay for a GPU runner.
                # Note that I always make sure all the tests pass prior to pushing into main.
                echo "Tested on local GPU machine!"